import type {
  BusinessProfile,
  ContactSnapshot,
  Lead,
  Profile,
  ProfileLink,
  SavedContact,
  User,
} from "../types";

const now = "2026-05-18T19:00:00.000Z";

export const mockUser: User = {
  id: "user_krish_pandey",
  email: "krish@cardiq.app",
  displayName: "Krish Pandey",
  role: "owner",
  accountPlan: "business",
  createdAt: now,
  updatedAt: now,
};

const profileLinks: readonly ProfileLink[] = [
  {
    id: "link_personal_instagram",
    profileId: "profile_personal",
    label: "Instagram",
    url: "https://instagram.com/krish",
    order: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "link_personal_calendar",
    profileId: "profile_personal",
    label: "Coffee Chat",
    url: "https://cal.com/krish/coffee",
    order: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "link_professional_linkedin",
    profileId: "profile_professional",
    label: "LinkedIn",
    url: "https://linkedin.com/in/krishpandey",
    order: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "link_professional_portfolio",
    profileId: "profile_professional",
    label: "Portfolio",
    url: "https://krishpandey.dev",
    order: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "link_acquaintance_email",
    profileId: "profile_acquaintance",
    label: "Email",
    url: "mailto:hello@cardiq.app",
    order: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "link_business_site",
    profileId: "profile_business",
    label: "Company Website",
    url: "https://cardiq.app",
    order: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "link_business_demo",
    profileId: "profile_business",
    label: "Book a Demo",
    url: "https://cal.com/cardiq/demo",
    order: 2,
    createdAt: now,
    updatedAt: now,
  },
];

const linksForProfile = (profileId: string) =>
  profileLinks.filter((link) => link.profileId === profileId);

export const mockBusinessProfile: BusinessProfile = {
  id: "business_cardiq",
  userId: mockUser.id,
  profileId: "profile_business",
  companyName: "CardIQ",
  jobTitle: "Founder",
  industry: "Professional Networking",
  websiteUrl: "https://cardiq.app",
  companyLogoUrl: "https://cardiq.app/logo.png",
  createdAt: now,
  updatedAt: now,
};

export const mockProfiles: readonly Profile[] = [
  {
    id: "profile_personal",
    userId: mockUser.id,
    type: "personal",
    publicSlug: "krish-personal",
    name: "Krish Pandey",
    headline: "Builder, traveler, and product thinker",
    bio: "Personal card for friends, community events, and casual introductions.",
    email: "krish@example.com",
    location: "Chicago, IL",
    links: linksForProfile("profile_personal"),
    isPublic: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "profile_professional",
    userId: mockUser.id,
    type: "professional",
    publicSlug: "krish-professional",
    name: "Krish Pandey",
    headline: "Software founder focused on practical mobile products",
    bio: "Professional profile for partners, hiring conversations, and investor intros.",
    email: "krish@cardiq.app",
    phone: "+1 312 555 0198",
    location: "Chicago, IL",
    links: linksForProfile("profile_professional"),
    isPublic: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "profile_acquaintance",
    userId: mockUser.id,
    type: "acquaintance",
    publicSlug: "krish",
    name: "Krish",
    headline: "Good to meet you",
    bio: "A lighter profile for quick exchanges and low-friction follow-up.",
    email: "hello@cardiq.app",
    links: linksForProfile("profile_acquaintance"),
    isPublic: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "profile_business",
    userId: mockUser.id,
    type: "business",
    publicSlug: "cardiq-krish",
    name: "Krish Pandey",
    headline: "Founder at CardIQ",
    bio: "Helping teams share smarter business cards and turn new contacts into action.",
    email: "sales@cardiq.app",
    location: "Chicago, IL",
    links: linksForProfile("profile_business"),
    isPublic: true,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockContactSnapshots: readonly ContactSnapshot[] = [
  {
    id: "snapshot_maya_reed",
    profileId: "external_maya_reed",
    type: "professional",
    name: "Maya Reed",
    headline: "Partnerships Lead at Northstar Labs",
    bio: "Explores partner channels for early-stage SaaS teams.",
    email: "maya@northstarlabs.com",
    location: "Austin, TX",
    links: [
      {
        id: "link_maya_linkedin",
        profileId: "external_maya_reed",
        label: "LinkedIn",
        url: "https://linkedin.com/in/mayareed",
        order: 1,
        createdAt: now,
        updatedAt: now,
      },
    ],
    capturedAt: now,
  },
  {
    id: "snapshot_noah_kim",
    profileId: "external_noah_kim",
    type: "business",
    name: "Noah Kim",
    headline: "Operations Director at Fieldstone",
    bio: "Runs events and field teams for a regional services company.",
    email: "noah@fieldstone.co",
    phone: "+1 415 555 0144",
    links: [
      {
        id: "link_noah_website",
        profileId: "external_noah_kim",
        label: "Company",
        url: "https://fieldstone.co",
        order: 1,
        createdAt: now,
        updatedAt: now,
      },
    ],
    capturedAt: now,
  },
  {
    id: "snapshot_ava_santos",
    profileId: "external_ava_santos",
    type: "personal",
    name: "Ava Santos",
    headline: "Community organizer and design mentor",
    bio: "Met at a local product meetup after a panel session.",
    email: "ava@example.com",
    links: [],
    capturedAt: now,
  },
];

export const mockSavedContacts: readonly SavedContact[] = [
  {
    id: "contact_maya_reed",
    userId: mockUser.id,
    profileId: "external_maya_reed",
    snapshot: mockContactSnapshots[0],
    notes: "Interested in co-marketing once the public beta is ready.",
    tags: ["partnership", "saas"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "contact_noah_kim",
    userId: mockUser.id,
    profileId: "external_noah_kim",
    snapshot: mockContactSnapshots[1],
    notes: "Asked about team plans for field reps.",
    tags: ["business", "operations"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "contact_ava_santos",
    userId: mockUser.id,
    profileId: "external_ava_santos",
    snapshot: mockContactSnapshots[2],
    tags: ["community"],
    createdAt: now,
    updatedAt: now,
  },
];

export const mockLeads: readonly Lead[] = [
  {
    id: "lead_maya_reed",
    ownerUserId: mockUser.id,
    savedContactId: "contact_maya_reed",
    snapshot: mockContactSnapshots[0],
    status: "qualified",
    source: "Product meetup",
    notes: "Send partner brief and beta timeline.",
    nextFollowUpAt: "2026-05-21T15:00:00.000Z",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "lead_noah_kim",
    ownerUserId: mockUser.id,
    savedContactId: "contact_noah_kim",
    snapshot: mockContactSnapshots[1],
    status: "contacted",
    source: "Conference scan",
    notes: "Follow up with pricing assumptions for 25 users.",
    nextFollowUpAt: "2026-05-23T17:30:00.000Z",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "lead_ava_santos",
    ownerUserId: mockUser.id,
    savedContactId: "contact_ava_santos",
    snapshot: mockContactSnapshots[2],
    status: "new",
    source: "Community event",
    createdAt: now,
    updatedAt: now,
  },
];
